agrego tabla reutilizable
Javascript-V-Reactjs/Tarea-2 pull request #1
Opened 2021-10-01 06:42 UTC by jramos22

2021-10-06 01:48 UTC, jocarrit requested changes

2021-10-06 01:48 UTC, jocarrit commented on src/components/List.js
> +                        }
Este approach esta bien, sin emabrgo la idea de la tarea es que otro developer que utilice la tabla, pueda pasarle estos encabezados de la tabla como childrens

2021-10-11 19:53 UTC, jocarrit approved these changes

2021-10-20 02:14 UTC, closed without merging

2021-10-20 02:15 UTC, jramos22 commented
Agrego tarea 3